version: "3"
services:
  web:
    container_name: evolving_solutions_url_shortener_api
    image: evolvingsoftware/evolving_solutions_url_shortener_api:alpha
    ports:
      - "8844:8844"
    environment:
      - BASE_URL=https://evolveurl.co
      - MONGODB_URI=mongodb://evolvingadmin:Spr!ngW!nter20@2@evolveurl.co:27017/evolving_solutions?directConnection=true&retryWrites=true
  mongodb:
    container_name: mongodb
    image: mongo:5.0
    ports:
      - "27017:27017"
    # add user and password to mongodb
    command: --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=evolvingadmin
      - MONGO_INITDB_ROOT_PASSWORD=Spr!ngW!nter20@2
    environment:
      - MONGO_INITDB_DATABASE=evolving_solutions